# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [2]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [23]:
#code from the solutions 
print(np.ones(10))
print(np.array(range(21)))
print(np.ones((5, 5), dtype=int))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [26]:
#code from solutions
x = np.random.randn(3, 3, 3)
x.reshape(27)

array([ 0.96808707, -0.97082378, -0.36250019, -2.19204948,  1.20749584,
       -1.43839176, -0.02653361,  0.67320672,  0.87291743,  1.26554502,
        0.49882405,  0.00484909, -0.5812148 , -0.01737702,  0.63208352,
        1.81409261,  0.4714711 ,  1.4716033 , -0.40462322, -1.20430351,
       -1.22296515,  0.24424947,  0.33472367,  0.93881136, -2.03187774,
        1.42943155,  0.45000716])

# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [27]:
arr5 = np.linspace(1, 10, 20, dtype="int")
print(arr5)

np.linspace(1, 10, 20)

[ 1  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10]


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [21]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

In [22]:
20

20

In [28]:
#Code goes here
a[3,4]

20

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [29]:
# Code come here
a[1:,3:]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [30]:
# Code comes here

<function ndarray.sum>

## 2.6 

Calculate the sum of each row in `a`.

In [31]:
# Code comes here
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
# Code comes here

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [34]:
# Codes comes here
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [36]:
# Code comes here
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"
df = pd.read_csv(url)
df

country             food_category  consumption  co2_emmission
0      Argentina                      Pork        10.51          37.20
1      Argentina                   Poultry        38.66          41.53
2      Argentina                      Beef        55.48        1712.00
3      Argentina               Lamb & Goat         1.56          54.63
4      Argentina                      Fish         4.36           6.96
...          ...                       ...          ...            ...
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh                      Rice       171.73         219.76
1428  Bangladesh                  Soybeans         0.61           0.27
1429  Bangladesh   Nuts inc. Peanut Butter         0.72           1.27

[1430 rows x 4 columns]

## 2.10 

How many rows and columns are there in the dataframe?

In [37]:
#Code comes here
df.shape

(1430, 4)

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [38]:
# Code comes here
df["co2_emmission"].mean()

74.383993006993

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [40]:
# Code comes here
df.iloc[df['co2_emmission'].idmax()]

AttributeError: 'Series' object has no attribute 'idmax'

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [ ]:
#code comes here

## 2.14

Which country consumes the least amount of beef per person per year?


In [42]:
# code comes here
(df.query("food_category == 'Beef'")
   .sort_values(by="consumption")
   .head(1))

country food_category  consumption  co2_emmission
1410  Liberia          Beef         0.78          24.07

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [44]:
# code comes here
meat = ['Poultry', 'Pork', 'Fish', 'Lamb & Goat', 'Beef']
df["co2_emmission"][df['food_category'].isin(meat)].sum()

74441.13

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [45]:
# code comes here
meat = ['Poultry', 'Pork', 'Fish', 'Lamb & Goat', 'Beef']
df["co2_emmission"][~df['food_category'].isin(meat)].sum()

31927.98

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.